name: proto-cookbook-dev
channels:
  - conda-forge
dependencies:
  - jupyterlab
  - mystmd
  - jupyterlab-myst
  - pandas
  - xarray
  - numpy
  - metpy
  - matplotlib
  - cartopy 
  - scipy 
  - pickle
  - cmweather 
  - herbie-data
  - datetime
